name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

# Necessário para o deploy nativo no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Credenciais do Banco de Dados
        run: |
          # Pega de secrets (caso tenha criado como Secret) ou vars (caso tenha criado como Variável)
          URL="${{ secrets.DATABASE_URL || vars.DATABASE_URL }}"
          TOKEN="${{ secrets.DATABASE_TOKEN || vars.DATABASE_TOKEN }}"
          
          # Reescreve o arquivo config.js inteiro de forma robusta
          cat <<EOF > config.js
          window.ENV = {
              DATABASE_URL: '$URL',
              DATABASE_TOKEN: '$TOKEN'
          };
          EOF
          echo "Credenciais injetadas no config.js!"

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Faz o upload de todos os arquivos da pasta raiz do projeto

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
