name: Deploy GitHub Pages

on:
  push:
    branches:
      - main # Dispara a cada push na branch principal

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Configurar Credenciais do Banco de Dados 🔧
        run: |
          # Pega de secrets (caso tenha criado como Secret) ou vars (caso tenha criado como Variável)
          URL="${{ secrets.DATABASE_URL || vars.DATABASE_URL }}"
          TOKEN="${{ secrets.DATABASE_TOKEN || vars.DATABASE_TOKEN }}"
          
          # Reescreve o arquivo config.js inteiro de forma robusta
          cat <<EOF > config.js
          window.ENV = {
              DATABASE_URL: '$URL',
              DATABASE_TOKEN: '$TOKEN'
          };
          EOF
          echo "Credenciais injetadas no config.js!"

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # Diretório com os arquivos estáticos do site
          branch: gh-pages # Branch destino do deploy
